services:
  ndpid:
    image: ndpi-observe-ci:latest
    privileged: true
    network_mode: host
    entrypoint: ["/src/ndpid"]
    environment:
      - IFACE=${IFACE:-eth0}
    command: ["-i", "${IFACE:-wlp9s0f0}", "-p", "19197"]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./labs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9092:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./labs/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana:/var/lib/grafana/dashboards:ro
    ports:
      - "3002:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
