/* SPDX-License-Identifier: Apache-2.0
 * ndpid — TC eBPF + nDPI userspace daemon
 *
 * Usage: ndpid -i <interface> [-p <prometheus_port>] [-s <cli_socket>]
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <time.h>
#include <getopt.h>
#include <poll.h>
#include <net/if.h>
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>

/* Generated by: bpftool gen skeleton bpf/ndpi_observe.bpf.o */
#include "../bpf/ndpi_observe.skel.h"

#include "ndpi_engine.h"
#include "unix_socket.h"
#include "prometheus.h"

static volatile int g_running = 1;

static void sig_handler(int sig)
{
    (void)sig;
    g_running = 0;
}

static int ring_buf_cb(void *ctx, void *data, size_t size)
{
    if (size < sizeof(struct ndpi_obs_flow_event))
        return 0;

    ndpi_engine_t *e     = ((void **)ctx)[0];
    int           *vfd_p = ((void **)ctx)[1];

    ndpi_engine_process(e, (struct ndpi_obs_flow_event *)data, *vfd_p);
    return 0;
}

static void usage(const char *prog)
{
    fprintf(stderr,
        "Usage: %s -i <interface> [-p <port>] [-s <socket>]\n"
        "  -i  Network interface to observe (required)\n"
        "  -p  Prometheus metrics port (default: %d)\n"
        "  -s  CLI socket path (default: %s)\n",
        prog, PROMETHEUS_PORT, CLI_SOCK_PATH);
}

int main(int argc, char **argv)
{
    const char *ifname     = NULL;
    int         prom_port  = PROMETHEUS_PORT;
    const char *sock_path  = CLI_SOCK_PATH;

    int opt;
    while ((opt = getopt(argc, argv, "i:p:s:h")) != -1) {
        switch (opt) {
        case 'i': ifname    = optarg; break;
        case 'p': prom_port = atoi(optarg); break;
        case 's': sock_path = optarg; break;
        case 'h':
        default:
            usage(argv[0]);
            return opt == 'h' ? 0 : 1;
        }
    }

    if (!ifname) {
        fprintf(stderr, "error: -i <interface> is required\n");
        usage(argv[0]);
        return 1;
    }

    int ifindex = (int)if_nametoindex(ifname);
    if (ifindex == 0) {
        fprintf(stderr, "error: interface %s not found\n", ifname);
        return 1;
    }

    signal(SIGINT,  sig_handler);
    signal(SIGTERM, sig_handler);

    /* Increase RLIMIT_MEMLOCK for BPF maps */
    struct rlimit rl = { 512UL * 1024 * 1024, 512UL * 1024 * 1024 };
    setrlimit(RLIMIT_MEMLOCK, &rl);

    /* ── Load and verify eBPF skeleton ────────────────────────────────── */
    struct ndpi_observe_bpf *skel = ndpi_observe_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "error: failed to open/load eBPF skeleton\n");
        return 1;
    }

    /* ── Attach TC hooks ───────────────────────────────────────────────── */
    LIBBPF_OPTS(bpf_tc_hook, hook_in,
        .ifindex      = ifindex,
        .attach_point = BPF_TC_INGRESS);
    LIBBPF_OPTS(bpf_tc_hook, hook_eg,
        .ifindex      = ifindex,
        .attach_point = BPF_TC_EGRESS);
    LIBBPF_OPTS(bpf_tc_opts, opts_in,
        .handle   = 1,
        .priority = 1,
        .prog_fd  = bpf_program__fd(skel->progs.ndpi_observe_ingress));
    LIBBPF_OPTS(bpf_tc_opts, opts_eg,
        .handle   = 1,
        .priority = 1,
        .prog_fd  = bpf_program__fd(skel->progs.ndpi_observe_egress));

    /* Create clsact qdisc (ignore EEXIST) */
    bpf_tc_hook_create(&hook_in);
    hook_eg.attach_point = BPF_TC_EGRESS;
    bpf_tc_hook_create(&hook_eg);

    if (bpf_tc_attach(&hook_in, &opts_in) < 0) {
        fprintf(stderr, "error: failed to attach TC ingress on %s\n", ifname);
        ndpi_observe_bpf__destroy(skel);
        return 1;
    }
    if (bpf_tc_attach(&hook_eg, &opts_eg) < 0) {
        fprintf(stderr, "warning: failed to attach TC egress on %s\n", ifname);
        /* Continue — ingress-only is still useful */
    }

    fprintf(stderr, "ndpid: observing %s\n", ifname);

    /* ── Map file descriptors ──────────────────────────────────────────── */
    int verdict_fd  = bpf_map__fd(skel->maps.verdict_map);
    int app_cnt_fd  = bpf_map__fd(skel->maps.app_counters);

    /* ── Ring buffer ───────────────────────────────────────────────────── */
    ndpi_engine_t engine;
    if (ndpi_engine_init(&engine) < 0) {
        fprintf(stderr, "error: failed to initialize nDPI\n");
        ndpi_observe_bpf__destroy(skel);
        return 1;
    }

    void *rb_ctx[2] = { &engine, &verdict_fd };
    struct ring_buffer *rb = ring_buffer__new(
        bpf_map__fd(skel->maps.flow_events), ring_buf_cb, rb_ctx, NULL);
    if (!rb) {
        fprintf(stderr, "error: failed to create ring buffer\n");
        ndpi_engine_destroy(&engine);
        ndpi_observe_bpf__destroy(skel);
        return 1;
    }

    /* ── CLI Unix socket ──────────────────────────────────────────────── */
    int cli_fd = unix_socket_init(sock_path);
    if (cli_fd < 0) {
        fprintf(stderr, "warning: failed to create CLI socket at %s: %s\n",
                sock_path, strerror(errno));
    }

    /* ── Prometheus HTTP ──────────────────────────────────────────────── */
    int prom_fd = prometheus_init(prom_port);
    if (prom_fd < 0) {
        fprintf(stderr, "warning: failed to start Prometheus on port %d: %s\n",
                prom_port, strerror(errno));
    } else {
        fprintf(stderr, "ndpid: Prometheus metrics on :%d/metrics\n", prom_port);
    }
    if (cli_fd >= 0)
        fprintf(stderr, "ndpid: CLI socket at %s\n", sock_path);

    /* ── Main event loop ──────────────────────────────────────────────── */
    time_t last_age = time(NULL);

    struct pollfd pfds[3];
    int nfds = 0;

    /* Ring buffer fd for poll */
    int rb_fd = ring_buffer__epoll_fd(rb);
    if (rb_fd >= 0) {
        pfds[nfds].fd     = rb_fd;
        pfds[nfds].events = POLLIN;
        nfds++;
    }
    if (cli_fd >= 0) {
        pfds[nfds].fd     = cli_fd;
        pfds[nfds].events = POLLIN;
        nfds++;
    }
    if (prom_fd >= 0) {
        pfds[nfds].fd     = prom_fd;
        pfds[nfds].events = POLLIN;
        nfds++;
    }

    while (g_running) {
        int ret = poll(pfds, nfds, 200 /* ms */);
        if (ret < 0) {
            if (errno == EINTR) continue;
            break;
        }

        /* Drain ring buffer */
        ring_buffer__poll(rb, 0);

        /* Handle CLI requests */
        if (cli_fd >= 0) {
            for (int i = 0; i < nfds; i++) {
                if (pfds[i].fd == cli_fd && (pfds[i].revents & POLLIN))
                    unix_socket_handle(cli_fd, &engine, app_cnt_fd);
            }
        }

        /* Handle Prometheus scrapes */
        if (prom_fd >= 0) {
            for (int i = 0; i < nfds; i++) {
                if (pfds[i].fd == prom_fd && (pfds[i].revents & POLLIN))
                    prometheus_handle(prom_fd, &engine, app_cnt_fd);
            }
        }

        /* Age flows every 10 seconds */
        time_t now = time(NULL);
        if (now - last_age >= 10) {
            ndpi_engine_age(&engine);
            last_age = now;
        }
    }

    fprintf(stderr, "ndpid: shutting down\n");

    /* ── Cleanup ──────────────────────────────────────────────────────── */
    ring_buffer__free(rb);
    ndpi_engine_destroy(&engine);

    bpf_tc_detach(&hook_in, &opts_in);
    bpf_tc_detach(&hook_eg, &opts_eg);
    bpf_tc_hook_destroy(&hook_in);
    bpf_tc_hook_destroy(&hook_eg);
    ndpi_observe_bpf__destroy(skel);

    if (cli_fd >= 0)  unix_socket_destroy(cli_fd, sock_path);
    if (prom_fd >= 0) prometheus_destroy(prom_fd);

    return 0;
}
