/*
 * ndpi_ml_labels.h — generated by train/train_mcp.py
 * DO NOT EDIT — regenerate with: python3 train/train_mcp.py <features.csv>
 */
#ifndef NDPI_ML_LABELS_H
#define NDPI_ML_LABELS_H

#include <stdint.h>

#define NDPI_ML_N_CLASSES            5
#define NDPI_ML_CONFIDENCE_THRESHOLD 0.6f

static const uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES] = {
    203,  /* [0] github  */
    124,  /* [1] youtube */
     74,  /* [2] steam   */
    189,  /* [3] zoom    */
    307,  /* [4] mcp     */
};

#endif /* NDPI_ML_LABELS_H */
