/*
 * ndpi_ml_labels.h - generated by train/train.py
 * DO NOT EDIT - regenerate with: python3 train/train.py <features.csv>
 */
#ifndef NDPI_ML_LABELS_H
#define NDPI_ML_LABELS_H

#include <stdint.h>

#define NDPI_ML_N_CLASSES            19
#define NDPI_ML_CONFIDENCE_THRESHOLD 0.55f

/* Class names in m2cgen output order. Proto IDs resolved at runtime
 * via ndpi_get_protocol_id() in ndpi_engine_init(). */
static const char *ndpi_ml_label_names[NDPI_ML_N_CLASSES] = {
    "Adnxs",
    "Akamaiedge",
    "Amazon",
    "AmazonAWS",
    "Cloudflare",
    "Co",
    "Criteo",
    "Fastly",
    "Google",
    "GoogleServices",
    "Microsoft",
    "NetFlix",
    "Pinterest",
    "Reddit",
    "Split",
    "Spotify",
    "Statuspage",
    "Twitch",
    "eBay",
};

/* Filled at runtime by ndpi_engine_init(). 0 = unresolved/unknown. */
extern uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES];

#endif /* NDPI_ML_LABELS_H */
