/* SPDX-License-Identifier: Apache-2.0
 * ML classification wrapper — calls the compiled RF model.
 */
#include "ndpi_ml.h"
#include "ndpi_ml_labels.h"
#include <math.h>
#include <string.h>
#include <ndpi/ndpi_api.h>

/* Defined in ndpi_ml_model.c (generated by m2cgen from scikit-learn RF) */
void score(double *input, double *output);

/* Resolved at runtime by ndpi_ml_init() — names → nDPI protocol IDs. */
uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES] = {0};

void ndpi_ml_init(struct ndpi_detection_module_struct *ndpi)
{
    for (int i = 0; i < NDPI_ML_N_CLASSES; i++) {
        ndpi_ml_label_to_proto[i] = ndpi_get_protocol_id(
            ndpi, (char *)ndpi_ml_label_names[i]);
    }
}

uint16_t ndpi_ml_classify(const ndpi_ml_features_t *feat)
{
    double input[NDPI_ML_N_FEATURES] = {
        feat->pkt_len_mean,  feat->pkt_len_std,
        feat->pkt_len_min,   feat->pkt_len_max,  feat->pkt_len_total,
        feat->iat_mean_s,    feat->iat_std_s,
        feat->iat_min_s,     feat->iat_max_s,
        feat->duration_s,    feat->n_pkts,
        feat->proto,         feat->dport,
        feat->first_pkt_len, feat->last_pkt_len,
    };

    double scores[NDPI_ML_N_CLASSES];
    score(input, scores);

    int best = 0;
    for (int i = 1; i < NDPI_ML_N_CLASSES; i++)
        if (scores[i] > scores[best])
            best = i;

    if ((float)scores[best] < NDPI_ML_CONFIDENCE_THRESHOLD)
        return 0;  /* NDPI_PROTOCOL_UNKNOWN */

    return ndpi_ml_label_to_proto[best];
}
