/*
 * ndpi_ml_labels.h — generated by scripts/ml/train.py (vpp-ndpi).
 * DO NOT EDIT — regenerate with: python scripts/ml/train.py
 */
#ifndef NDPI_ML_LABELS_H
#define NDPI_ML_LABELS_H

#include <stdint.h>

#define NDPI_ML_N_CLASSES            5
#define NDPI_ML_CONFIDENCE_THRESHOLD 0.6f

static const uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES] = {
    203,  /* [0] github  */
    133,  /* [1] netflix */
     74,  /* [2] steam   */
    124,  /* [3] youtube */
    189,  /* [4] zoom    */
};

#endif /* NDPI_ML_LABELS_H */
