#!/usr/bin/env python3
"""
train_mcp.py — retrain the ndpi-observe Random Forest with MCP as a 6th class.

Usage:
    # 1. Collect features (run ndpid with --dump-features while using Claude Code):
    #    sudo ndpid -i wlp9s0f0 --dump-features /tmp/features.csv
    #
    # 2. Label MCP flows:
    #    python3 train/label_mcp.py /tmp/features.csv /tmp/features_labeled.csv
    #
    # 3. Train and regenerate model:
    #    python3 train/train_mcp.py /tmp/features_labeled.csv

Requires: pandas scikit-learn m2cgen
    pip install pandas scikit-learn m2cgen
"""

import sys
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import m2cgen as m2c

FEATURES = [
    "pkt_len_mean", "pkt_len_std", "pkt_len_min", "pkt_len_max", "pkt_len_total",
    "iat_mean_s", "iat_std_s", "iat_min_s", "iat_max_s",
    "duration_s", "n_pkts", "proto", "dport",
    "first_pkt_len", "last_pkt_len",
]

# Must match ndpi_ml_label_to_proto[] index order in ndpi_ml_labels.h:
#   [0]=Github(203), [1]=Netflix(133), [2]=Steam(74), [3]=Youtube(124),
#   [4]=Zoom(189), [5]=MCP(307)
TARGET_CLASSES = ["Github", "Netflix", "Steam", "Youtube", "Zoom", "MCP"]

OUT_MODEL  = os.path.join(os.path.dirname(__file__), "../daemon/ndpi_ml_model.c")
OUT_LABELS = os.path.join(os.path.dirname(__file__), "../daemon/ndpi_ml_labels.h")

LABELS_TEMPLATE = """\
/*
 * ndpi_ml_labels.h — generated by train/train_mcp.py
 * DO NOT EDIT — regenerate with: python3 train/train_mcp.py <features.csv>
 */
#ifndef NDPI_ML_LABELS_H
#define NDPI_ML_LABELS_H

#include <stdint.h>

#define NDPI_ML_N_CLASSES            6
#define NDPI_ML_CONFIDENCE_THRESHOLD 0.6f

static const uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES] = {{
    203,  /* [0] github  */
    133,  /* [1] netflix */
     74,  /* [2] steam   */
    124,  /* [3] youtube */
    189,  /* [4] zoom    */
    307,  /* [5] mcp     */
}};

#endif /* NDPI_ML_LABELS_H */
"""

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <labeled_features.csv>")
        sys.exit(1)

    csv_path = sys.argv[1]
    print(f"Loading {csv_path}…")
    df = pd.read_csv(csv_path)

    # Keep only the target classes
    df = df[df["label"].isin(TARGET_CLASSES)].copy()
    print(f"Rows after filtering to target classes: {len(df)}")
    print(df["label"].value_counts().to_string())

    if len(df) < 50:
        print("ERROR: too few samples — collect more traffic first")
        sys.exit(1)

    for cls in TARGET_CLASSES:
        count = (df["label"] == cls).sum()
        if count < 5:
            print(f"WARNING: class '{cls}' has only {count} samples — may underfit")

    X = df[FEATURES].values.astype(float)
    y = df["label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y if len(df) > 50 else None)

    print(f"\nTraining RandomForest ({len(X_train)} train, {len(X_test)} test)…")
    clf = RandomForestClassifier(
        n_estimators=100,
        max_depth=12,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = (y_pred == y_test).mean()
    print(f"Accuracy: {acc:.3f}\n")
    print(classification_report(y_test, y_pred, labels=TARGET_CLASSES, zero_division=0))

    # Feature importances
    print("Top-5 features:")
    importances = sorted(zip(FEATURES, clf.feature_importances_), key=lambda x: -x[1])
    for name, imp in importances[:5]:
        print(f"  {name:20s} {imp:.4f}")

    # Generate C model — class order must match TARGET_CLASSES
    clf.classes_ = TARGET_CLASSES  # m2cgen uses this for output ordering
    print(f"\nGenerating C model → {OUT_MODEL}")
    c_code = m2c.export_to_c(clf)
    with open(OUT_MODEL, "w") as f:
        f.write(c_code)

    # Regenerate labels header
    print(f"Writing labels header → {OUT_LABELS}")
    with open(OUT_LABELS, "w") as f:
        f.write(LABELS_TEMPLATE)

    print("\nDone. Rebuild ndpid:")
    print("  cd /home/denys/projects/ndpi-observe && make")

if __name__ == "__main__":
    main()
