#!/usr/bin/env python3
"""
train.py — train a generalized RF that mimics SNI/nDPI classification using
only traffic-shape features (no hostnames / no SNI as input).

Usage:
    python3 train/train.py /tmp/ndpi-train/features.csv [min_samples_per_class]

Inputs:
    features.csv with columns:
        label, pkt_len_*, iat_*, duration_s, n_pkts, proto, dport,
        first_pkt_len, last_pkt_len

Outputs:
    daemon/ndpi_ml_model.c   (m2cgen-generated RF inference code)
    daemon/ndpi_ml_labels.h  (class names; proto IDs resolved at runtime)
"""

import sys
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import m2cgen as m2c

FEATURES = [
    "pkt_len_mean", "pkt_len_std", "pkt_len_min", "pkt_len_max", "pkt_len_total",
    "iat_mean_s", "iat_std_s", "iat_min_s", "iat_max_s",
    "duration_s", "n_pkts", "proto", "dport",
    "first_pkt_len", "last_pkt_len",
]

# Labels that are useless / generic — drop from training data.
EXCLUDE = {"Unknown", "TLS", "HTTP", "QUIC", "DNS", "MDNS", "DHCP", "NTP",
           "SSDP", "ICMP", "ICMPV6", "STUN", "RTP", "OCSP"}

OUT_MODEL  = os.path.join(os.path.dirname(__file__), "../daemon/ndpi_ml_model.c")
OUT_LABELS = os.path.join(os.path.dirname(__file__), "../daemon/ndpi_ml_labels.h")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <features.csv> [min_samples_per_class=20]")
        sys.exit(1)

    csv_path = sys.argv[1]
    min_samples = int(sys.argv[2]) if len(sys.argv) > 2 else 20

    print(f"Loading {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"Total rows: {len(df)}")

    df = df[~df["label"].isin(EXCLUDE)].copy()
    print(f"After excluding generic labels: {len(df)}")

    counts = df["label"].value_counts()
    keep = counts[counts >= min_samples].index.tolist()
    df = df[df["label"].isin(keep)].copy()
    print(f"\nClasses with >= {min_samples} samples ({len(keep)}):")
    print(df["label"].value_counts().to_string())

    if len(keep) < 2:
        print("ERROR: need at least 2 classes")
        sys.exit(1)

    classes = sorted(keep)
    X = df[FEATURES].values.astype(float)
    y = df["label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y)

    print(f"\nTraining RandomForest ({len(X_train)} train, {len(X_test)} test)...")
    clf = RandomForestClassifier(
        n_estimators=150,
        max_depth=14,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = (y_pred == y_test).mean()
    print(f"\nOverall accuracy: {acc:.3f}\n")
    print(classification_report(y_test, y_pred, zero_division=0))

    print("Top features:")
    for name, imp in sorted(zip(FEATURES, clf.feature_importances_),
                            key=lambda x: -x[1])[:8]:
        print(f"  {name:18s} {imp:.4f}")

    # m2cgen output uses sklearn's classes_ ordering
    sk_classes = list(clf.classes_)

    print(f"\nGenerating C model -> {OUT_MODEL}")
    c_code = m2c.export_to_c(clf)
    with open(OUT_MODEL, "w") as f:
        f.write(c_code)

    # Labels header — names only; proto IDs resolved at runtime via nDPI
    print(f"Writing labels header -> {OUT_LABELS}")
    with open(OUT_LABELS, "w") as f:
        f.write("/*\n * ndpi_ml_labels.h - generated by train/train.py\n")
        f.write(" * DO NOT EDIT - regenerate with: python3 train/train.py <features.csv>\n */\n")
        f.write("#ifndef NDPI_ML_LABELS_H\n#define NDPI_ML_LABELS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define NDPI_ML_N_CLASSES            {len(sk_classes)}\n")
        f.write("#define NDPI_ML_CONFIDENCE_THRESHOLD 0.55f\n\n")
        f.write("/* Class names in m2cgen output order. Proto IDs resolved at runtime\n")
        f.write(" * via ndpi_get_protocol_id() in ndpi_engine_init(). */\n")
        f.write(f"static const char *ndpi_ml_label_names[NDPI_ML_N_CLASSES] = {{\n")
        for c in sk_classes:
            f.write(f'    "{c}",\n')
        f.write("};\n\n")
        f.write("/* Filled at runtime by ndpi_engine_init(). 0 = unresolved/unknown. */\n")
        f.write("extern uint16_t ndpi_ml_label_to_proto[NDPI_ML_N_CLASSES];\n\n")
        f.write("#endif /* NDPI_ML_LABELS_H */\n")

    print(f"\nClasses (m2cgen order): {sk_classes}")
    print("\nNext: rebuild ndpid")


if __name__ == "__main__":
    main()
